### ISSUE TITLE
Step 2 Completion

### ISSUE THREAD

**Issue by echavemann** [echavemann/learnsomething#1]
should not take more than a day of heads down.

**Comment by minnce** [comment]
taking over completing step 2, accidently blew up half of it but it will be done soon 💀

**Comment by minnce** [comment]
https://instagram.com/gdsc_northwestern?igshid=MmU2YjMzNjRlOQ==

**Comment by echavemann** [comment]
ideation and design done by me, pending rules and tests my chris
