### ISSUE TITLE
Step 4 Completion

### ISSUE THREAD

**Issue by echavemann** [echavemann/learnsomething#8]
Ideation is done, need dev time.

**Comment by echavemann** [comment]
hard sla of 24hr
- needs slower factorizing algorithm and then thresholds determined, potentially readme work

**Comment by minnce** [comment]
Completed, closing issue.

**Comment by minnce** [comment]
https://github.com/echavemann/learnsomething/commit/d2c1fd907d831387ef86cd499487c33e2b5be27f
Link to commit that completes issue.
